gitlab:
   image: 'gitlab/gitlab-ce:latest'
   restart: always
   container_name: gitlab
   hostname: 'pc.example.com'
   environment:
     GITLAB_OMNIBUS_CONFIG: |
       external_url 'http://pc.gitlab.com'
       # Add any other gitlab.rb configuration here, each on its own line
   ports:
     - '80:80'
     - '443:443'
     - '22:22'
   volumes:
     - gitlab_config:/etc/gitlab
     - gitlab_data:/var/opt/gitlab