  v2ray:
    image: v2ray/official
    container_name: v2ray
    restart: always
    volumes:
      - ./etc:/etc/v2ray
      - ./log/v2ray:/var/log/v2ray
    ports:
      - 55520:55520
    command: ["v2ray", "-config=/etc/v2ray/config.json"]
